server:
  port: 8772

#指定注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#服务的名称
spring:
  application:
    name: weight-record-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weight_record?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    # 开启驼峰
    property-naming-strategy: LOWER_CAMEL_CASE
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  data:
    mongodb:
      database: weight_record
      host: localhost
      port: 27017
