server:
  port: 8770

#指定注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#服务的名称
spring:
  application:
    name: ahuiali-common-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/words?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
